// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinavSistemi.API.Data;

#nullable disable

namespace SinavSistemi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502170013_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciSinavi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Notu")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("SinavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinavId");

                    b.HasIndex("OgrenciId", "SinavId")
                        .IsUnique();

                    b.ToTable("OgrenciSinavlari");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocaId")
                        .HasColumnType("int");

                    b.HasKey("DersId");

                    b.HasIndex("HocaId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Hoca", b =>
                {
                    b.Property<int>("HocaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocaId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HocaId");

                    b.ToTable("Hocalar");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.OgrenciDersi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId", "DersId")
                        .IsUnique();

                    b.ToTable("OgrenciDersleri");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Salon", b =>
                {
                    b.Property<int>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonId"));

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalonId");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Sinav", b =>
                {
                    b.Property<int>("SinavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavId"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SinavTarihi")
                        .HasColumnType("date");

                    b.HasKey("SinavId");

                    b.HasIndex("DersId");

                    b.HasIndex("SalonId");

                    b.ToTable("Sinavlar");
                });

            modelBuilder.Entity("OgrenciSinavi", b =>
                {
                    b.HasOne("SinavSistemi.API.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciSinavlari")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinavSistemi.API.Models.Sinav", "Sinav")
                        .WithMany("OgrenciSinavlari")
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Ders", b =>
                {
                    b.HasOne("SinavSistemi.API.Models.Hoca", "Hoca")
                        .WithMany("Dersler")
                        .HasForeignKey("HocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoca");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.OgrenciDersi", b =>
                {
                    b.HasOne("SinavSistemi.API.Models.Ders", "Ders")
                        .WithMany("OgrenciDersleri")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinavSistemi.API.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersleri")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Sinav", b =>
                {
                    b.HasOne("SinavSistemi.API.Models.Ders", "Ders")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinavSistemi.API.Models.Salon", "Salon")
                        .WithMany("Sinavlar")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Ders", b =>
                {
                    b.Navigation("OgrenciDersleri");

                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Hoca", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersleri");

                    b.Navigation("OgrenciSinavlari");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Salon", b =>
                {
                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("SinavSistemi.API.Models.Sinav", b =>
                {
                    b.Navigation("OgrenciSinavlari");
                });
#pragma warning restore 612, 618
        }
    }
}
